version: "3.7"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=proyectofinal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  web:
    build: .
    command: python app.py
    volumes:
      - ./back:/code
    ports:
      - "5000:5000"
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080
